### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by cognitivetech** [JimmXinu/EpubSplit#10]
Working fine with other books... must be something to do with its structure

```
$ python3 epubsplit.py --split-by-section books/Charlottes-Web_E-B-White.epub 
Traceback (most recent call last):
  File "/home/asimo/jamstack/summarization/workspace/epubsplit.py", line 1354, in <module>
    main(sys.argv[1:])
  File "/home/asimo/jamstack/summarization/workspace/epubsplit.py", line 1285, in main
    lines = epubO.get_split_lines()
  File "/home/asimo/jamstack/summarization/workspace/epubsplit.py", line 734, in get_split_lines
    if href in self.get_toc_map():
  File "/home/asimo/jamstack/summarization/workspace/epubsplit.py", line 665, in get_toc_map
    textnode = navpoint.getElementsByTagName("text")[0].firstChild
IndexError: list index out of range
```

[Charlottes-Web_E-B-White.epub.zip](https://github.com/JimmXinu/EpubSplit/files/15047526/Charlottes-Web_E-B-White.epub.zip)

(edit: as i explore this more, I wonder if it might be easier to unpack the epub archive and use the html files directly)

**Comment by JimmXinu** [comment]
This [version of epubsplit.py](https://github.com/JimmXinu/EpubSplit/blob/aab288a7538b459a9f3fff8a7a98c3fad960fcd2/epubsplit.py) addresses this issue.

Arguably, I shouldn't fix this.  The epub is technically in violation of the standard.  

I'm not likely to do a full release of the Calibre plugin for this unless it comes up again.

### Details
[NCX DTD](http://www.daisy.org/z3986/2005/ncx-2005-1.dtd) says a `<navPoint>` tag requires one or more `<navLabel>` tags inside it, which this epub doesn't have.  

OTOH, epubsplit.py was looking for a `<text>` tag inside an assumed `<navLabel>` tag and the `<text>` tag isn't required if there's an `<audio>` tag.

#### DTD
```
<!-- Navigation Point - contains description(s) of target, as well as a pointer to 
entire content of target.
Hierarchy is represented by nesting navPoints.  "class" attribute describes the kind 
of structural unit this object represents (e.g., "chapter", "section").
-->
<!ELEMENT navPoint (navLabel+, content, navPoint*)>
<!-- Revised, 3/29/2004:  Removed onFocus/onBlur -->
<!-- Revised, 3/29/2004:  Removed value -->
<!-- Revised, 3/31/2004:  Removed pageRef -->
<!-- Revised, 4/5/2004:  Added playOrder -->
<!ATTLIST navPoint
  id    ID      #REQUIRED
  class    CDATA    #IMPLIED
  playOrder CDATA       #REQUIRED
>

<!-- Navigation Label - Contains a description of a given <navMap>, <navPoint>, 
<navList>, or <navTarget> in various media for presentation to the user. Can be 
repeated so descriptions can be provided in multiple languages. -->
<!ELEMENT navLabel (((text, audio?) | audio), img?)>
<!ATTLIST navLabel
  %i18n; 
>
```
