### ISSUE TITLE
Error: cannot import name 'SafeConfigParser' from 'configparser'

### ISSUE THREAD

**Issue by Linus045** [JimmXinu/EpubSplit#13]
I'm getting the following error when starting calibre with the plugin installed (from the plugin interface inside calibre).

calibre version: calibre (calibre 7.13)
Plugin version: 3.48.0
Python version: 3.12.4
OS: Linux

```
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 147, in __init__
    ac = self.init_iaction(action)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 165, in init_iaction
    ac = action.load_actual_plugin(self)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/customize/__init__.py", line 659, in load_actual_plugin
    ac = getattr(importlib.import_module(mod), cls)(gui,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 205, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.epubsplit.epubsplit_plugin", line 19, in <module>
    from six.moves.configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
```

I removed the plugin inside calibre, cloned the repo, applied the following diff and build and installed it with the commands inside the `make_plugin.bat` script.

This seems to fix the Issue, however I'm not in the slightest familiar with the `six.moves.configparser` library or your code and have no Idea if this breaks stuff, it did however let me start calibre with no errors and split my epub file:

```diff
diff --git a/epubsplit_plugin.py b/epubsplit_plugin.py
index c3cf8fc..e48ef14 100644
--- a/epubsplit_plugin.py
+++ b/epubsplit_plugin.py
@@ -16,7 +16,7 @@ from functools import partial
 from datetime import datetime
 
 import six
-from six.moves.configparser import SafeConfigParser
+from six.moves.configparser import ConfigParser
 from six.moves import range
 from six import text_type as unicode
```

**Comment by JimmXinu** [comment]
That change won't break anything--that import isn't actually needed by EpubSplit.  
Removed in c13dbd71723d5f2e900fb43e6802f2b28126fb47

Python 3 at some point renamed `SafeConfigParser` to just `ConfigParser`.  The `six` package is supposed to handle that sort of nonsense, but apparently not as my other plugin that does use configparser has special handling for it.

I would be curious to know, however, if you use a vendor packaged version of Calibre or the [official release](https://calibre-ebook.com/download)?

**Comment by Linus045** [comment]
I'm using Arch Linux.
Here's the package info:
<https://archlinux.org/packages/extra/x86_64/calibre>

You can see the package PKGBUILD here: <https://gitlab.archlinux.org/archlinux/packaging/packages/calibre/-/blob/main/PKGBUILD>

It just downloads from the main website as far as I can tell (line 83) 
I'm not really familiar how packaging works on Linux/Arch, but I hope this answers your question at least.
