### ISSUE TITLE
big file split

### ISSUE THREAD

**Issue by lakedai** [JimmXinu/EpubSplit#2]
i have a epub file size 275M. when using epubsplit in calibre, it freezes to dead.
what can i do?

**Comment by JimmXinu** [comment]
Without seeing the epub in question, I can only speculate that you're using Calibre 32bit bit on Windows.  The 64bit version allows for a lot more memory and has helped others.

**Comment by lakedai** [comment]
i have tried again and wait for a long time and eventualy it become alive. that was a miracle! thank you for your job!
for your reference here is the epub : http://www.j9p.com/down/537722.html

**Comment by JimmXinu** [comment]
I can't read that page and clicking what I thought was the download link didn't work.  I'm not going to click randomly on a site I don't know and can't read.

If it did work eventually, it's probably just a ton of files in the epub, not broken.
