### ISSUE TITLE
Support publication date per article when splitting news feeds

### ISSUE THREAD

**Issue by sbk** [JimmXinu/EpubSplit#5]
## Problem

When splitting news feeds into its articles, the publication date is set to the download date.

## Idea

Luckily the publication date is already included within the .epub file as "article_date" in the HTML TOC files of every feed.

But it is not used.

Maybe we could iterate through all TOC files and collect the publication dates to the articles.

## Technical Solution

Build a dict() that contains href -> pubdate.

Iterate through the .epub file by walking through the directories "feed_\<n\>" while n starts with 0.

Every "feed_\<n\>" directory contains an index.html, which also includes the "article_date".

Parse article date, add to dictionary.

Re-use this information later, when splited.epub is generated.

## Additional note

I am just reading through the source code and trying to understand it.

Maybe I could try to implement this by myself, if the suggestion is considered reasonable.

**Comment by JimmXinu** [comment]
While this appears theoretically doable, it seems extremely situational.  I'm a bit wary of opening the door to modifying EpubSplit for specific niche cases...

OTOH, by all means make a version for your own use that includes that feature.  

Or if there's a significant number of users who want it, I may consider it for the published version.  Most discussion of EpubSplit plugin happens in the [MR forum thread](https://www.mobileread.com/forums/showthread.php?t=178799).

**Comment by sbk** [comment]
Thank you for the quick response!

Yes, it's a niche use case. It makes sense to skip the implementation for the main plugin here. I will try to implement it myself or find some other way to split news feeds into its articles from the beginning. Maybe a custom recipe could also achieve what I am looking for.

I will close this issue and head right into the MR forum thread next time, before opening an issue.

Thank you!
