### ISSUE TITLE
support split by section from the command line

### ISSUE THREAD

**Issue by FenTheFox** [JimmXinu/EpubSplit#8]
what the title says. something like 
`calibre-debug --run-plugin EpubSplit --split-by-section -- <epub>`
with each split file being named based on the table of contents name.

**Comment by JimmXinu** [comment]
The ToC entry text may not be a valid file name--and what is valid varies by OS.  Plus there's no guarantee that ToC entries are uniquely named.

How about adding `--split-by-section` and `--output-dir` options and each output file will be named `<lineno>-<outputname>`.  New options:
```
Options:
  -h, --help            show this help message and exit
  -o OUTPUT, --output=OUTPUT
                        Set OUTPUT file, Default: split.epub
  --output-dir=OUTPUTDIROPT
                        Set OUTPUT directory, Default: presend working
                        directory
  --split-by-section    Create a new epub from *each* of the listed line
                        sections instead of one containing all.  Splits all
                        sections if no lines numbers are given. Each split
                        will be named <lineno>-<outputname> and placed in the
                        output-dir.
  -t TITLE, --title=TITLE
                        Use TITLE as the metadata title.  Default: '<original
                        epub title> Split' or ToC entry with --split-by-
                        section
```
So running:
`epubsplit.py "Dracula - Bram Stoker.epub" --split-by-section 11 12 13 --output-dir=test --output=Dracula.epub`
Will result in three files:
```
test/0011-Dracula.epub
test/0012-Dracula.epub
test/0013-Dracula.epub
```
or, if you don't give a `--output` option:
```
test/0011-split.epub
test/0012-split.epub
test/0013-split.epub
```
`--output-dir` dir must already exist.

**Comment by FenTheFox** [comment]
that would be awesome

**Comment by JimmXinu** [comment]
I've committed(c3df7c652346b5f47d8afca1036f5cb00da88215) that change and attached an updated [EpubSplit.zip](https://github.com/JimmXinu/EpubSplit/files/11205436/EpubSplit.zip) since that seems to be the version you use.

FYI, your initial post has the option order wrong.  `--` needs to be right after `EpubSplit`:
`calibre-debug --run-plugin EpubSplit -- --split-by-section <epub>`

Please give it a try and let me know what you think.

**Comment by FenTheFox** [comment]
ok, this might just be my weird case but, i'm trying to split a magazine that has one section per page, eg `calibre-debug --run-plugin EpubSplit -- yurihime.epub` outputs the following [output.txt](https://github.com/JimmXinu/EpubSplit/files/11205474/output.txt)
what i really want is the equivalent of the plugin mode where it splits based on toc sections, so everything after a title until the next title gets put in the same epub

**Comment by JimmXinu** [comment]
Looks like you forgot the `--split-by-section` option.

And you will get 488 separate epubs if you do on that file--because it's one split file for *every* 'section'.  

I forgot the plugin version concatenated sections without ToC.

**Comment by JimmXinu** [comment]
v3.6.0 released
